# Generated by Django 2.1.3 on 2018-11-20 04:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=20, verbose_name='主题')),
                ('desc', models.CharField(default='', max_length=50, verbose_name='描述')),
                ('image', models.ImageField(default='default.png', upload_to='images/covers/%Y', verbose_name='封面')),
                ('created', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '相册',
                'verbose_name_plural': '相册',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albums.Album', verbose_name='所属相册')),
            ],
            options={
                'verbose_name': '图片',
                'verbose_name_plural': '图片',
            },
        ),
    ]
