# Generated by Django 2.1.3 on 2018-11-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='img',
            field=models.ImageField(default='default.png', upload_to='images/album/%Y', verbose_name='图片'),
        ),
    ]
