# Generated by Django 2.1.3 on 2018-11-21 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='desc',
            field=models.CharField(default='', max_length=100, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='article',
            name='subtitle',
            field=models.CharField(default='', max_length=50, verbose_name='副标题'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=50, verbose_name='标题'),
        ),
    ]
