# Generated by Django 2.1.3 on 2018-11-21 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20181121_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.CharField(default='', max_length=20, verbose_name='标签'),
        ),
    ]
