# Generated by Django 2.1.3 on 2018-11-21 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.CharField(choices=[('c++', 'C++'), ('java', 'Java'), ('python', 'Python'), ('kaggle', 'Kaggle')], default='python', max_length=20, verbose_name='文章类型'),
        ),
    ]
