# Generated by Django 2.1.3 on 2018-11-21 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20181121_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.CharField(choices=[('C++', 'C++'), ('Java', 'Java'), ('Python', 'Python'), ('Kaggle', 'Kaggle')], default='python', max_length=20, verbose_name='文章类型'),
        ),
    ]
